spring.application.name=smart-eco
# =========================
# SERVER
# =========================
server.port=8080

# =========================
# H2 DATABASE
# =========================
spring.datasource.url=jdbc:h2:mem:smarteco
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola H2 (IMPORTANTE para ver datos)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# JWT (opcional base si lo quieres parametrizar)
# =========================
jwt.secret=9f3c7a2b6d4e8f1c0a7b9d2e5f6c8a1d4e7f9b2c6d8a1e3f5c7b9d0a2e4f6c8
jwt.expiration=86400000